// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjbpNyVZ2B4aROjtFs1YWZWI2RdtvXeA',
    appId: '1:549736954894:web:e4a23813fb751e6ffed05f',
    messagingSenderId: '549736954894',
    projectId: 'demoapp-eaabf',
    authDomain: 'demoapp-eaabf.firebaseapp.com',
    storageBucket: 'demoapp-eaabf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpSFqELbqCd-nTdiQRIcGHAVx0syn9Vc',
    appId: '1:549736954894:android:312b818b516ee994fed05f',
    messagingSenderId: '549736954894',
    projectId: 'demoapp-eaabf',
    storageBucket: 'demoapp-eaabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4JtxCCEu0Ba1YeSXCv9PQQJmE1lJdy4',
    appId: '1:549736954894:ios:7b80769ba2e9414ffed05f',
    messagingSenderId: '549736954894',
    projectId: 'demoapp-eaabf',
    storageBucket: 'demoapp-eaabf.appspot.com',
    iosClientId:
        '549736954894-drdcsqh4vjvuarqbrdees4bqf6upmfe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.powereact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4JtxCCEu0Ba1YeSXCv9PQQJmE1lJdy4',
    appId: '1:549736954894:ios:7b80769ba2e9414ffed05f',
    messagingSenderId: '549736954894',
    projectId: 'demoapp-eaabf',
    storageBucket: 'demoapp-eaabf.appspot.com',
    iosClientId:
        '549736954894-drdcsqh4vjvuarqbrdees4bqf6upmfe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.powereact',
  );
}
